function CreateCoefPanel( source,event )
global Strings
b=1/8;
a=2/19;
ref = source.String;
load('../data/CurrentVars');
var.popup = source.Value;
parent = findobj('Tag','mainpanel');
        var.currentpanel =2 ;
        inputPanel = uipanel('Parent',parent,...
                             'Title',Strings.PanelTitles(2),...
                             'Position',[0,0.5,0.5,0.5-0.05]);
                     uicontrol('Parent',inputPanel,...
                               'Style','popup',...
                               'Units','normalized',...
                               'String',Strings.coef.labels,...
                               'Position',[5*a,b/2,4*a,b],...
                               'Value',var.popup,...
                               'Callback',@CreateCoefPanel);                   
        labels = Strings.coef.(source.String{source.Value}).labels;
        units  = Strings.coef.(source.String{source.Value}).units;

        for j=1:5
            if(1+2*(j-1)<=length(labels))         
            uicontrol('Parent',inputPanel,...
                               'Style','text',...
                               'String',labels(1+2*(j-1)),...
                               'Units','normalized',...
                               'Position',[a/2,1-(b/2+b)*j,a,b]);
            uicontrol('Parent',inputPanel,...
                               'Style','edit',...
                               'Units','normalized',...
                               'Position',[2*a,1-(b/2+b)*j,a,b],...
                               'String',var.(labels{1+2*(j-1)}),...
                               'Tag',labels{1+2*(j-1)},...
                               'Callback',@savedata);
            uicontrol('Parent',inputPanel,...
                               'Style','text',...
                               'String',units(1+2*(j-1)),...
                               'Units','normalized',...
                               'Position',[3*a+a/2,1-(b/2+b)*j,a,b]);
            end
            if(2*j<=length(labels))
                     uicontrol('Parent',inputPanel,...
                               'Style','text',...
                               'String',labels(2*j),...
                               'Units','normalized',...
                               'Position',[5*a,1-(b/2+b)*j,a,b]);
                     uicontrol('Parent',inputPanel,...
                               'Style','edit',...
                               'Units','normalized',...
                               'Position',[6*a+a/2,1-(b/2+b)*j,a,b],...
                               'String',var.(labels{2*j}),...
                               'Tag',labels{2*j},...
                               'Callback',@savedata);
                     uicontrol('Parent',inputPanel,...
                               'Style','text',...
                               'String',units(2*j),...
                               'Units','normalized',...
                               'Position',[8*a,1-(b/2+b)*j,a,b]);
            end
        end
    save('../data/CurrentVars','var');
end

