function InitialConditionsWindow( src,event )
global Strings
VarStrings
b=1/6;
a=2/21;
load('./data/CurrentVars.mat','var');
fig = figure(3);
set(fig,'Menubar','none');
set(fig,'Units','normalized');
set(fig,'Position',[0.2,0.2,0.3,0.5]);
set(fig,'Name','Initial Conditions');
set(fig,'NumberTitle','off');
mainpanel = uipanel('Parent',fig,...
                    'Units','normalized');
                
bg = uibuttongroup('Parent',mainpanel,...
                   'Position',[b+b/2,1-a,4*b,a]);
            uicontrol(bg,...
                      'Style','radiobutton',...
                      'Units','normalized',...
                      'Position',[0.1,0,0.5,1],...
                      'String','Manual')
            uicontrol(bg,...
                      'Style','radiobutton',...
                      'Units','normalized',...
                      'Position',[0.5,0,0.5,1],...
                      'String','Trim Values',...
                      'Callback',@CalcTrim)
           
for i=1:length(Strings.Init.labels)
    
    uicontrol('Parent',mainpanel,...
              'Units','normalized',...
              'Style','text',...
              'String',Strings.Init.labels{i},...
              'Position',[0,1-a-(a+a/2)*i,b,a])
    for j=1:length(Strings.(Strings.Init.labels{i}).labels)
          uicontrol('Parent',mainpanel,...
              'Units','normalized',...
              'Style','edit',...
              'Position',[j*(b+b/2),1-a-(a+a/2)*i,b,a],...
              'String',var.(Strings.(Strings.Init.labels{i}).labels{j}),...
              'Tag',Strings.(Strings.Init.labels{i}).labels{j},...
              'Callback',@savedata)
          uicontrol('Parent',mainpanel,...
              'Units','normalized',...
              'Style','text',...
              'String',Strings.(Strings.Init.labels{i}).labels{j},...
              'Position',[j*(b+b/2),1-(a+a/2)*i,b,a/2])
    end
end
end

